services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"   
      - "443:443"   
      
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      onbbu:
        aliases:
          - proxy.onbbu.ar

  qlub:
    image: njavilas/qlub:1.0
    volumes:
      - ./subdomains.json:/app/subdomains.json
      - ./nginx.conf:/app/nginx.conf

networks:
  company:
    name: company_new